export const FETH_PRODUCTS = 'FETH_PRODUCTS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const SAVE_PRODUCT = 'SAVE_PRODUCT';